# .github/workflows/publish-playwright.yml

name: Build and Push Playwright Service

on:
  push:
    branches:
      - main   # 改成你常用分支

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Playwright image
      uses: docker/build-push-action@v5
      with:
        context: ./apps/playwright-service-ts
        push: true
        tags: sylvia666/firecrawl-playwright:latest
